### ISSUE TITLE
Homepage of the website

### ISSUE THREAD

**Issue by jkugsiya** [jkugsiya/TechnoIndiaNJR#1]
Create a homepage of the website in reference to the original website: www.technonjr.org.
Things to keep in mind:
1. The page should be responsive that is it should work well on both mobiles and desktop screens. 
2. Good coding practice should be followed.
3. The Pull request need not be in a single commit.

**Comment by m-ohit-s** [comment]
I want to work on this issue

**Comment by jkugsiya** [comment]
Thanks @m-ohit-s. You can work on it.
