### ISSUE TITLE
About us page of the website

### ISSUE THREAD

**Issue by jkugsiya** [jkugsiya/TechnoIndiaNJR#2]
Create an about us page of the website refer to the original website: www.technonjr.org.

Things to keep in mind:

1. The page should be responsive that is it should work well on both mobiles and desktop screens.
2. Good coding practice should be followed.
3. The Pull request need not be in a single commit.

About us tab includes 4 total pages that will be assigned individually to a single person and this issue will be closed in collectively 4 pull requests:

- [x] About us Mainpage. (@joshimehul)
- [x] About us -> Code of Conduct. (@sahuvivek2000)
- [x] About us -> IQAC (@sahuvivek2000)
- [x] About us -> Policy (@sahuvivek2000)

**Comment by joshimehul** [comment]
can i work on this issue ?

**Comment by jkugsiya** [comment]
Yeah sure @joshimehul. Thanks!

**Comment by jkugsiya** [comment]
@joshimehul This issue has multiple sub-issues to work on (Read the edited issue). What page would you specifically like to work on.

**Comment by joshimehul** [comment]
I would like to work on About us Main page.

**Comment by sahuvivek2000** [comment]
I want to work on this issue

**Comment by jkugsiya** [comment]
> I want to work on this issue

@sahuvivek2000 read the issue explanation and tell me on which page do you want to work?

**Comment by sahuvivek2000** [comment]
policy

**Comment by jkugsiya** [comment]
OK, @sahuvivek2000  I am assigning the policy page to you. It will not show in the assignees section but when you'll create a pull request I'll assign you the PR.

**Comment by sahuvivek2000** [comment]
I want to work on IQAC

**Comment by jkugsiya** [comment]
@sahuvivek2000 you can work on IQAC.

**Comment by sahuvivek2000** [comment]
I want to work on > Code of Conduct.
