### ISSUE TITLE
Include footer and links to other available pages in `Contact Us` page.

### ISSUE THREAD

**Issue by jkugsiya** [jkugsiya/TechnoIndiaNJR#21]
Include footer and links to other available pages in `Contact Us` page.

**Comment by m-ohit-s** [comment]
Can I work on this issue

**Comment by m-ohit-s** [comment]
What are the links for social media handles?

**Comment by jkugsiya** [comment]
> What are the links for social media handles?

You can take that from the original website.

**Comment by m-ohit-s** [comment]
Ok
And should I upload same links for same pages or #'s are fine
