### ISSUE TITLE
Improve navbar navigation for small screen sizes.

### ISSUE THREAD

**Issue by jkugsiya** [jkugsiya/TechnoIndiaNJR#23]
As we can see in the original website we can click on individual items to navigate to a specific page from the navbar menu.
![image](https://user-images.githubusercontent.com/42642325/120140409-1eef9500-c1f8-11eb-8f05-08f3b5479a80.png)
Look at specific `About Us` `Departments` and `Placements` page menu items, we can go to their mainpage as well as other pages available in it when expanded but we don't have the same functionality, i.e. we cannot go to their parent or main page we can just navigate to the pages included in `About Us` `Departments` and `Placements` page.
![image](https://user-images.githubusercontent.com/42642325/120140578-78f05a80-c1f8-11eb-8bd4-0e30fbe49334.png)

Implement a solution to solve this problem so that user can go to `About Us` `Departments` and `Placements` main page.

**Comment by sahuvivek2000** [comment]
I want to work on this issue
