### ISSUE TITLE
Create Departments page of the website.

### ISSUE THREAD

**Issue by jkugsiya** [jkugsiya/TechnoIndiaNJR#4]
Create a departments page of the website refer to the original website: www.technonjr.org.

Things to keep in mind:

The page should be responsive that is it should work well on both mobiles and desktop screens.
Good coding practice should be followed.
The Pull request need not be in a single commit.

The Departments page include 10 different pages and each individual page will be assigned one at a time, this issue will be closed after successfully merging below 10 PRs:

- [x] Departments Mainpage. (@jkugsiya)
- [x] Computer Science Engineerging and Information Technology (CSE & IT) (@m-ohit-s)
- [x] Electronics and Communication Engineering (ECE) (@m-ohit-s)
- [x] Mechanical Engineering (ME) (@jeakansh)
- [x] Electrical Engineering (EE) (@sahuvivek2000)
- [x] Civil Engineering (CE) (@jeakansh)
- [x] Applied Science and Humanities (@m-ohit-s)
- [x] Adjunct Faculties (@jkugsiya)
- [x] Research (@jkugsiya)
- [x] Projects (@sahuvivek2000)

**Comment by jeakansh** [comment]
I want to claim the issue.

**Comment by jkugsiya** [comment]
@jeakansh I have updated this issue description, kindly go through it and tell me what sub-issue would you like to work on?

**Comment by jeakansh** [comment]
I want to claim the CS Eng. & IT Page

**Comment by m-ohit-s** [comment]
I want to work on CSE Department Page

**Comment by m-ohit-s** [comment]
Can I work on CSE Department Page

**Comment by jkugsiya** [comment]
Sure @m-ohit-s!

> Can I work on CSE Department Page

**Comment by jeakansh** [comment]
I want to claim the `Civil Engineering (CE)` part of the issue #4

**Comment by sahuvivek2000** [comment]
I want to work on Electrical Engineering (EE)

**Comment by m-ohit-s** [comment]
I want to work on Electronics and Communication Engineering (ECE)

**Comment by sahuvivek2000** [comment]
I want to work on projects

**Comment by m-ohit-s** [comment]
I want to work on applied science and humanities

**Comment by jkugsiya** [comment]
> I want to work on projects

Ok @sahuvivek2000 assigning that to you.
