### ISSUE TITLE
Create Navigation Bar/Header .

### ISSUE THREAD

**Issue by jkugsiya** [jkugsiya/TechnoIndiaNJR#8]
Create NavBar/Header of the website refer to the original website: www.technonjr.org.

Things to keep in mind:

1. The menu should be responsive that is it should work well on both mobiles and desktop screens.
2. Good coding practice should be followed.
3. The Pull request need not be in a single commit.

**Comment by sahuvivek2000** [comment]
I'll work on this

**Comment by jkugsiya** [comment]
Thanks @sahuvivek2000 . Assigning this issue to you .
