### ISSUE TITLE
Create a footer referring to the original website: www.technonjr.org

### ISSUE THREAD

**Issue by jkugsiya** [jkugsiya/TechnoIndiaNJR#9]
Things to keep in mind:

1. The footer should be responsive that is it should work well on both mobiles and desktop screens.
2. Good coding practice should be followed.
3. The Pull request need not be in a single commit.

**Comment by Godwindaniel10** [comment]
hi @jkugsiya i will like to solve this issue

**Comment by jkugsiya** [comment]
Sure @Godwindaniel10 refer to the original website's footer: www.technonjr.org

**Comment by Godwindaniel10** [comment]
hi @jkugsiya , can you be more clear on the footer.

what are the informations you want to add to the footer.
and what exactly do you want to do ?

**Comment by jkugsiya** [comment]
Actually we want to replicate this website: www.technonjr.org with some little theme changes and responsiveness. Add the same information in the footer as in the mentioned website.

**Comment by Godwindaniel10** [comment]
ok cool,  on it...

**Comment by Godwindaniel10** [comment]
@jkugsiya  can i add more info to the footer ( e.g about the website , logo,) ?

**Comment by jkugsiya** [comment]
> @jkugsiya can i add more info to the footer ( e.g about the website , logo,) ?

First, do the former as our milestone has to be done. After doing so, if you want to improvise then open a new issue suggesting the changes you would like to perform that would be nice to have.

**Comment by Godwindaniel10** [comment]
ok great

**Comment by jkugsiya** [comment]
@Godwindaniel10 Are you still working on this issue?

**Comment by jkugsiya** [comment]
@Godwindaniel10 Unassigning you as no reply.

**Comment by sahuvivek2000** [comment]
Can I work on this

**Comment by jkugsiya** [comment]
Sure @sahuvivek2000, go for it!

**Comment by Godwindaniel10** [comment]
hi @jkugsiya .

Well i am almost done working on the issue, reason for my ( no reply ) was because my house light went off for 24 hours and all my devices went off.

well its cool..it was a pleasure.

have a nice day today @jkugsiya
